In [2]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [3]:
A = np.random.randn(10)
A

array([-0.27037412, -1.18485941, -0.51542491, -2.24298289,  0.83204843,
       -0.50325772,  0.42189527,  1.83546913, -1.53154413, -1.10673288])

In [4]:
B = np.random.randn(10)
B

array([ 0.61066921,  0.30931293, -0.27567524, -0.37502559,  0.57533703,
       -0.27063261, -1.13078814, -0.31948659, -0.80001175,  0.0849548 ])

In [7]:
np.add(A,B)

array([ 0.34029509, -0.87554648, -0.79110015, -2.61800847,  1.40738546,
       -0.77389033, -0.70889287,  1.51598253, -2.33155588, -1.02177808])

In [8]:
np.maximum(A,B)

array([ 0.61066921,  0.30931293, -0.27567524, -0.37502559,  0.83204843,
       -0.27063261,  0.42189527,  1.83546913, -0.80001175,  0.0849548 ])

In [9]:
website = 'www.google.com'
import webbrowser
webbrowser.open(website)

True

In [10]:
np.minimum(A,B)

array([-0.27037412, -1.18485941, -0.51542491, -2.24298289,  0.57533703,
       -0.50325772, -1.13078814, -0.31948659, -1.53154413, -1.10673288])

In [12]:
A = np.array([1,2,3,4])

In [13]:
B = np.array([100,200,300,400])

In [14]:
condition = np.array([True,True,False, False])

In [20]:
answer = [A_val if cond else B_val for A_val, B_val, cond in zip(A, B, condition)]

In [21]:
answer

[1, 2, 300, 400]

In [22]:
answer2 = np.where(condition, A, B)

In [23]:
answer2

array([  1,   2, 300, 400])

In [25]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.sum()

45

In [29]:
arr.sum(0)

array([12, 15, 18])

In [32]:
arr.sum(1)

array([ 6, 15, 24])

In [33]:
from numpy.random import randn

In [36]:
myArr = randn(5)

In [37]:
myArr

array([-0.10571559,  2.53666348,  0.44324058,  0.91260559,  0.97250715])

In [39]:
num = np.arange(5)
num

array([0, 1, 2, 3, 4])

In [46]:
(np.eye(5))

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])